[build]
target = "../../../src/x86_64-mochios.json"

[unstable]
build-std = ["core", "alloc", "panic_abort"]
json-target-spec = true

[target.x86_64-mochios]
rustflags = [
    "-C", "link-arg=-nostdlib",
    "-C", "link-arg=--no-gc-sections",
    "-C", "relocation-model=pic",
    "-C", "link-arg=-pie",
    "-C", "llvm-args=-stackrealign",
]
